//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrandApp.UI.DB.PRODUCTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public int Id { get; set; }
        public string MaskedCardNo { get; set; }
        public string ErranderID { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string CVV { get; set; }
        public string Exp { get; set; }
    }
}
